### This project predicts which passengers survived the Titanic shipwreck

Data Set: Titanic DataSet

Problem: To predict the survival of Titanic passengers based on Pclass,Sex,Age and Fare Attributes

Model Used: Decision Tree.


In [ ]:
import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [55]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [56]:
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [57]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [58]:
df.shape

(891, 5)

In [59]:
int(df["Age"].mean())

29

In [60]:
df["Age"]=df["Age"].replace(np.nan,int(df["Age"].mean()))

In [61]:
df["Sex"]=df["Sex"].replace({'male':1,"female":2})

In [62]:
inputs = df.drop('Survived',axis='columns')
inputs.head()

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

In [63]:
y = df.Survived

In [64]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(inputs)
X

array([[ 0.82737724, -0.73769513, -0.58165904, -0.50244517],
       [-1.56610693,  1.35557354,  0.64932701,  0.78684529],
       [ 0.82737724,  1.35557354, -0.27391253, -0.48885426],
       ...,
       [ 0.82737724,  1.35557354, -0.04310264, -0.17626324],
       [-1.56610693, -0.73769513, -0.27391253, -0.04438104],
       [ 0.82737724, -0.73769513,  0.18770724, -0.49237783]])

In [74]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [72]:
from sklearn.model_selection import ShuffleSplit #(for selecting variables from uniform distribution)
from sklearn.model_selection import cross_val_score
cv=ShuffleSplit(n_splits=5,random_state=0,test_size=0.2)
print("Accuracy Score is:",np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=cv)))

Accuracy Score is: 0.7910614525139665


In [67]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [68]:
model.predict([[-1.56610693,  1.35557354,  0.64932701,  0.78684529]])

array([1])

In [69]:
model.predict(scaler.fit_transform([[1,1,38.0,71.2833]]))

array([0])