In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
# step 2 :  import data set
data = pd.read_csv('breast-cancer-wisconsin.data.txt')

In [6]:
data.head()

id  clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0  1000025                5               1                1              1   
1  1002945                5               4                4              5   
2  1015425                3               1                1              1   
3  1016277                6               8                8              1   
4  1017023                4               1                1              3   

   single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
0                       2           1            3              1        1   
1                       7          10            3              2        1   
2                       2           2            3              1        1   
3                       3           4            3              7        1   
4                       2           1            3              1        1   

   class  
0      2  
1      2  
2      2  
3      2  
4      2

In [7]:
# delete the unwanted id column
data.drop(['id'],axis =1,inplace=True)
data.head()

clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0                5               1                1              1   
1                5               4                4              5   
2                3               1                1              1   
3                6               8                8              1   
4                4               1                1              3   

   single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
0                       2           1            3              1        1   
1                       7          10            3              2        1   
2                       2           2            3              1        1   
3                       3           4            3              7        1   
4                       2           1            3              1        1   

   class  
0      2  
1      2  
2      2  
3      2  
4      2

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   clump_thickness         699 non-null    int64 
 1   unif_cell_size          699 non-null    int64 
 2   unif_cell_shape         699 non-null    int64 
 3   marg_adhesion           699 non-null    int64 
 4   single_epith_cell_size  699 non-null    int64 
 5   bare_nuclei             699 non-null    object
 6   bland_chrom             699 non-null    int64 
 7   norm_nucleoli           699 non-null    int64 
 8   mitoses                 699 non-null    int64 
 9   class                   699 non-null    int64 
dtypes: int64(9), object(1)
memory usage: 54.7+ KB


In [9]:
data=data.replace("?",np.nan)

In [10]:
data["bare_nuclei"]=data["bare_nuclei"].astype("float")

In [11]:
data.isnull().sum()

clump_thickness            0
unif_cell_size             0
unif_cell_shape            0
marg_adhesion              0
single_epith_cell_size     0
bare_nuclei               16
bland_chrom                0
norm_nucleoli              0
mitoses                    0
class                      0
dtype: int64

In [12]:
data["bare_nuclei"]=data["bare_nuclei"].replace(np.nan,data["bare_nuclei"].mean())

In [13]:
data.isnull().sum()

clump_thickness           0
unif_cell_size            0
unif_cell_shape           0
marg_adhesion             0
single_epith_cell_size    0
bare_nuclei               0
bland_chrom               0
norm_nucleoli             0
mitoses                   0
class                     0
dtype: int64

In [14]:
X = data.drop(['class'], axis =1)
y = data['class']
print(X.shape,"  ",X.ndim)
print(y.shape,"  ",y.ndim)

(699, 9)    2
(699,)    1


In [15]:
# split data into training and testing sections
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
neigh = KNeighborsClassifier(n_neighbors = 5)
neigh.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [18]:
y_pre = neigh.predict(X_test)
y_pre

array([4, 4, 2, 4, 4, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 4,
       4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 4, 4, 4, 4, 2, 2, 4, 2, 4,
       2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2,
       2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4,
       4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2,
       4, 4, 4, 2, 4, 2, 2, 2])

In [19]:
for i in y_pre:
    if(i == 2):
        print("benign")
    else:
        print("Maligant")

Maligant
Maligant
benign
Maligant
Maligant
benign
Maligant
benign
benign
Maligant
benign
benign
benign
benign
Maligant
benign
benign
Maligant
Maligant
benign
benign
Maligant
Maligant
benign
benign
benign
Maligant
benign
Maligant
Maligant
benign
benign
benign
benign
benign
benign
Maligant
benign
Maligant
benign
benign
Maligant
benign
Maligant
benign
benign
benign
benign
benign
benign
Maligant
Maligant
benign
benign
benign
Maligant
Maligant
Maligant
Maligant
Maligant
Maligant
benign
benign
Maligant
benign
Maligant
benign
benign
benign
Maligant
benign
benign
benign
benign
Maligant
Maligant
Maligant
benign
benign
benign
benign
benign
Maligant
Maligant
benign
benign
benign
benign
benign
Maligant
benign
benign
benign
benign
benign
Maligant
benign
benign
benign
Maligant
benign
benign
benign
Maligant
benign
benign
benign
benign
benign
Maligant
Maligant
benign
Maligant
Maligant
benign
benign
benign
Maligant
Maligant
benign
benign
benign
Maligant
benign
benign
Maligant
benign
benign
benign
benig

In [20]:
# calculating accuracy with test data
accuracy = neigh.score(X_test, y_test)
accuracy

0.9714285714285714

In [21]:
from sklearn.metrics import accuracy_score
print("Test set Accuracy: ", accuracy_score(y_test, y_pre))

Test set Accuracy:  0.9714285714285714


### Let's use StratifiedKFold to get accuracy score among various folds used for training and testing data

In [129]:
from sklearn.model_selection import StratifiedKFold # import KFold
kf = StratifiedKFold(n_splits=5) # Define the split - into 5 folds 


In [131]:
accuracy=[]
from sklearn.metrics import accuracy_score
for train_index,test_index in kf.split(X,y):
    print("train:",train_index,"test:",test_index)

    X_train, X_test,y_train, y_test = X.iloc[train_index], X.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
    neigh.fit(X_train,y_train)

    prediction=neigh.predict(X_test)

    score=accuracy_score(prediction,y_test)
    accuracy.append(score)
print(accuracy)

train: [105 106 107 109 111 112 113 117 122 123 124 126 128 132 142 146 149 151
 152 155 159 160 162 163 164 165 166 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193
 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211
 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229
 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247
 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265
 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283
 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301
 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319
 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337
 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355
 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373
 374 375 376 377 378 379 380 381 382 383 384

### Instead of writing above function, we can use cross_val_score function from sklearn.model_selection and ShuffleSplit from sklearn.model_selection for uniform selection of testing and training data

In [102]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
cv=ShuffleSplit(n_splits=5)
cross_val_score(KNeighborsClassifier(n_neighbors = 5),X,y, cv=5)

array([0.92857143, 0.94285714, 0.98571429, 0.98571429, 0.97841727])

In [108]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
cv=ShuffleSplit(n_splits=5,test_size=0.2,random_state=1)
cross_val_score(KNeighborsClassifier(n_neighbors = 5),X,y, cv=cv)

array([0.97142857, 0.97142857, 0.97142857, 0.95714286, 0.95      ])

### Thus KNeighborsClassifier is a model of good fit for detection of Breast cancer patients.